baseURL: "https://parttimenerd.github.io/"
defaultContentLanguage: "en"
title: "parttimenerd"
theme: "projects-theme"

params:
  nav:
    - label: "femto libs"
      url: /femto/
    - label: "jvm tools"
      url: /jvm-tools/
    - label: "experiments"
      url: /experiments/
  blog_url: "https://mostlynerdless.de"
