baseURL: "https://parttimenerd.github.io/"
defaultContentLanguage: "en"
title: "parttimenerd"
theme: "projects-theme"

params:
  nav:
    - label: "femto libs"
      url: /femto/
    - label: "supportability"
      url: /supportability/
  blog_url: "https://mostlynerdless.de"
