#!/usr/bin/env python3
"""
Reads data/categories.yaml
Writes data/<section>/static.yaml  for each collection

Fetches .tool.yaml from each tool repo's raw GitHub URL and merges in
website-side fields (id, group, no_sap).

Exit codes:
  0 — success, even if some tools were skipped due to warnings
  1 — data/categories.yaml is missing or unparseable
"""

import argparse
import os
import sys
import time
from pathlib import Path

import requests
import yaml

ROOT = Path(__file__).resolve().parent.parent
GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN", "")

REQUIRED_FIELDS = {"tag", "tagline", "tagline_short"}

SCHEMA_HEADER = """\
# ─────────────────────────────────────────────────────────────────────────────
# AUTO-GENERATED by scripts/fetch_tool_metadata.py — do not edit by hand.
# Edit .tool.yaml in each tool's repo, or data/categories.yaml for grouping.
# ─────────────────────────────────────────────────────────────────────────────

"""


def _get(url: str, headers: dict | None = None, timeout: int = 15, retries: int = 3) -> requests.Response:
    """GET with exponential backoff on 429 / 5xx."""
    headers = headers or {}
    delay = 2.0
    for attempt in range(retries):
        try:
            resp = requests.get(url, headers=headers, timeout=timeout)
            if resp.status_code in (429, 500, 502, 503, 504) and attempt < retries - 1:
                retry_after = float(resp.headers.get("Retry-After", delay))
                time.sleep(min(retry_after, 60))
                delay *= 2
                continue
            return resp
        except requests.exceptions.Timeout:
            if attempt < retries - 1:
                time.sleep(delay)
                delay *= 2
                continue
            raise
    raise RuntimeError(f"GET {url} failed after {retries} attempts")


class _LiteralStr(str):
    pass


def _literal_representer(dumper, data):
    return dumper.represent_scalar("tag:yaml.org,2002:str", data, style="|")


class _Dumper(yaml.Dumper):
    pass


_Dumper.add_representer(_LiteralStr, _literal_representer)


def _wrap(obj):
    if isinstance(obj, str):
        return _LiteralStr(obj) if "\n" in obj else obj
    if isinstance(obj, list):
        return [_wrap(i) for i in obj]
    if isinstance(obj, dict):
        return {k: _wrap(v) for k, v in obj.items()}
    return obj


def _raw_url(repo_url: str, filename: str) -> str:
    parts = repo_url.rstrip("/").replace("https://github.com/", "")
    return f"https://raw.githubusercontent.com/{parts}/HEAD/{filename}"


def _fetch_tool_yaml(repo_url: str) -> dict | None:
    url = _raw_url(repo_url, ".tool.yaml")
    headers = {}
    if GITHUB_TOKEN:
        headers["Authorization"] = f"token {GITHUB_TOKEN}"
    try:
        resp = _get(url, headers=headers, timeout=15)
        if resp.status_code == 404:
            print(f"  WARNING: .tool.yaml not found in {repo_url}", file=sys.stderr)
            return None
        resp.raise_for_status()
    except requests.RequestException as exc:
        print(f"  WARNING: network error fetching {repo_url}: {exc}", file=sys.stderr)
        return None

    try:
        data = yaml.safe_load(resp.text)
    except yaml.YAMLError as exc:
        print(f"  WARNING: YAML parse error in {repo_url}/.tool.yaml: {exc}", file=sys.stderr)
        return None

    if not isinstance(data, dict):
        print(f"  WARNING: .tool.yaml in {repo_url} is not a YAML mapping", file=sys.stderr)
        return None

    missing = REQUIRED_FIELDS - data.keys()
    if missing:
        print(
            f"  WARNING: .tool.yaml in {repo_url} missing required fields: {', '.join(sorted(missing))}",
            file=sys.stderr,
        )
        return None

    return data


def _repo_id(repo_url: str) -> str:
    return repo_url.rstrip("/").split("/")[-1]


def _build_static_yaml(tools: list[dict]) -> str:
    dumped = yaml.dump(
        _wrap(tools),
        Dumper=_Dumper,
        allow_unicode=True,
        default_flow_style=False,
        sort_keys=False,
        width=100,
    )
    return SCHEMA_HEADER + dumped


def fetch_section(section_id: str, collection: dict) -> list[dict]:
    tools = []
    for group in collection.get("groups", []):
        group_name = group["name"]

        for tool_entry in group.get("tools", []):
            repo_url = tool_entry.get("repo")
            if repo_url is None:
                print(f"  WARNING: tool entry in group '{group_name}' has no 'repo' key — skipping", file=sys.stderr)
                continue
            tool_id = _repo_id(repo_url)
            data = _fetch_tool_yaml(repo_url)
            if data is None:
                continue
            merged = {
                "id": tool_id,
                "group": group_name,
                **data,
            }
            if tool_entry.get("no_sap"):
                merged["no_sap"] = True
            tools.append(merged)
            print(f"  {tool_id}: ok")

        for fallback in group.get("fallback_tools", []):
            if not fallback.get("id"):
                print(f"  WARNING: fallback_tool entry in group '{group_name}' has no 'id' key — skipping", file=sys.stderr)
                continue
            merged = {"group": group_name, **fallback}
            tools.append(merged)
            print(f"  {fallback.get('id', '<unknown>')}: ok (fallback)")

    return tools


def main():
    parser = argparse.ArgumentParser(description="Fetch tool metadata from individual repos.")
    parser.add_argument(
        "--section",
        help="Only process this section (e.g. jvm-tools). Omit to process all.",
    )
    args = parser.parse_args()

    categories_path = ROOT / "data" / "categories.yaml"
    if not categories_path.exists():
        print(f"ERROR: {categories_path} not found", file=sys.stderr)
        sys.exit(1)

    try:
        categories = yaml.safe_load(categories_path.read_text())
    except yaml.YAMLError as exc:
        print(f"ERROR: failed to parse {categories_path}: {exc}", file=sys.stderr)
        sys.exit(1)

    for collection in categories.get("collections", []):
        section_id = collection["id"]
        if args.section and section_id != args.section:
            continue

        print(f"\n[{section_id}]")
        tools = fetch_section(section_id, collection)

        out_path = ROOT / "data" / section_id / "static.yaml"
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(_build_static_yaml(tools))
        print(f"  Wrote {len(tools)} tools to {out_path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
